#ifndef SHELLCONF_H
#define SHELLCONF_H

//#define SHELL_CMD_THREADS_ENABLED FALSE
#define SHELL_CMD_TEST_ENABLED FALSE
#define SHELL_USE_HISTORY TRUE
#define SHELL_USE_ESC_SEQ TRUE
#define SHELL_CMD_EXIT_ENABLED FALSE

#endif //SHELLCONF_H
